version: '3'
services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch-oss:6.5.0
    container_name: elasticsearch
    ports:
      - 9300:9300
      - 9200:9200
    networks:
    - esnet:
  logstash:
    image: "docker.elastic.co/logstash/logstash-oss:6.5.0"
    container_name: logstash
    ports:
      - 5044:5044
    networks:
    - esnet:
  kibana:
    image: "docker.elastic.co/kibana/kibana-oss:6.5.0"
    container_name: kibana
    ports:
      - "5601:5601"
    networks:
    - esnet:
